/*
 * Copyright 2026 Alibaba Group Holding Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.alibaba.openagentauth.core.protocol.wimse.workload.model;

import com.alibaba.openagentauth.core.util.ValidationUtils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;

/**
 * Request for getting workload information by workload ID.
 * <p>
 * This class encapsulates the parameters needed to retrieve information about
 * a specific agent workload. The workload ID is a WIMSE-defined identifier
 * that uniquely identifies a workload in the system.
 * </p>
 * <p>
 * According to WIMSE protocol, workload IDs are opaque identifiers that should
 * be treated as strings without any semantic meaning. They are used to reference
 * workloads in various operations such as token issuance, revocation, and querying.
 * </p>
 *
 * @see <a href="https://datatracker.ietf.org/doc/html/draft-ietf-wimse-workload-creds">draft-ietf-wimse-workload-creds</a>
 * @since 1.0
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class GetWorkloadRequest {

    /**
     * The WIMSE workload identifier.
     * <p>
     * This field is REQUIRED and uniquely identifies a workload in the system.
     * The workload ID is generated by the Agent IDP when a workload is created
     * and is used to reference the workload in subsequent operations.
     * </p>
     * <p>
     * The workload ID format is defined by the WIMSE protocol and should be
     * treated as an opaque string. Clients should not make any assumptions
     * about its structure or meaning.
     * </p>
     */
    @JsonProperty("workloadId")
    private final String workloadId;

    /**
     * Constructor for Jackson deserialization.
     *
     * @param workloadId the WIMSE workload identifier
     */
    @JsonCreator
    public GetWorkloadRequest(@JsonProperty("workloadId") String workloadId) {
        this.workloadId = workloadId;
    }

    /**
     * Constructor for builder pattern.
     *
     * @param builder the builder instance
     */
    private GetWorkloadRequest(Builder builder) {
        this.workloadId = builder.workloadId;
    }

    /**
     * Gets the WIMSE workload identifier.
     *
     * @return the workload identifier
     */
    public String getWorkloadId() {
        return workloadId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        GetWorkloadRequest that = (GetWorkloadRequest) o;
        return Objects.equals(workloadId, that.workloadId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(workloadId);
    }

    @Override
    public String toString() {
        return "GetWorkloadRequest{" +
                "workloadId='" + workloadId + '\'' +
                '}';
    }

    /**
     * Creates a new builder for {@link GetWorkloadRequest}.
     *
     * @return a new builder instance
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Builder for {@link GetWorkloadRequest}.
     * <p>
     * This builder provides a fluent API for constructing GetWorkloadRequest instances
     * with proper validation of required fields.
     * </p>
     */
    public static class Builder {

        /**
         * The WIMSE workload identifier.
         */
        private String workloadId;

        /**
         * Sets the WIMSE workload identifier.
         * <p>
         * This field is REQUIRED and must uniquely identify a workload in the system.
         * </p>
         *
         * @param workloadId the workload identifier
         * @return this builder instance
         */
        public Builder workloadId(String workloadId) {
            this.workloadId = workloadId;
            return this;
        }

        /**
         * Builds the {@link GetWorkloadRequest}.
         * <p>
         * This method validates that all required fields are present before
         * constructing the request object.
         * </p>
         *
         * @return the built get workload request
         * @throws IllegalArgumentException if any required field is null or empty
         */
        public GetWorkloadRequest build() {
            if (ValidationUtils.isNullOrEmpty(workloadId)) {
                throw new IllegalArgumentException("Workload ID is required");
            }
            return new GetWorkloadRequest(this);
        }
    }
}
